version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    networks:
      - bot-network
    ports:
      - "80:80"
      - "443:443"
      - "50000-65535:50000-65535/udp"
    command: ["python", "main.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"