version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["python", "bot.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"